spring:
  application:
    name: task-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: false

# Локальные настройки на случай недоступности Config Server
server:
  port: 8081

logging:
  level:
    org.example.task: DEBUG
    org.springframework.web: INFO
  file:
    name: logs/task-service.log