server:
  port: 8081

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics